
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
 /*
3.2. "Список задач"
Структура (см лекцию по типам данных)
+ название дела
+ время добавления (см helloWorld)
+ флаг выполненности дела (bool)
Структуру размещаем в сопоставление int8 => struct (см лекцию по типам данных)
должны быть доступны опции:
+ добавить задачу (должен в сопоставление заполняться последовательный целочисленный ключ)
- получить количество открытых задач (возвращает число)
+ получить список задач
+ получить описание задачи по ключу
+ удалить задачу по ключу
+ отметить задачу как выполненную по ключу
*/
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// Задание 3.2 "Список задач"
contract HomeWork_2 {
 
 //Инициализируем ключ для сопоставления задач
 int8 public key = 1;
//Инициализируем переменную для счёта открытых задач
 int8 public countOpenTasks = 0;
 
 //Создаём задачу (название задачи, время добавления, флаг выполнения)
 struct  Task {
        string taskName;
        uint32  timestamp;
        bool  mark;
    }

Task task;

//Создаём сопоставление по целочисленному ключу
mapping (int8=>Task) public tasksArray;


// Modifier that allows to accept some external messages
modifier checkOwnerAndAccept {
	// Check that message was signed with contracts key.
		
	require(msg.pubkey() == tvm.pubkey(), 102);
			tvm.accept();
		_;
	} 

//Функция создания задачи и сопоставления ей порядкового целочисленного значения
function setTask(string name, bool mark) public  checkOwnerAndAccept {
    key += 1;
    task.taskName = name;
    task.timestamp = now;
    task.mark = mark;
    tasksArray[key] = task;

//счётчик открытых задач
    if (task.mark==true){
        countOpenTasks +=1;
        }
}

//- отметить задачу как выполненную по ключу
function setTaskAsDone(int8 taskKeyWhichIsDone) public checkOwnerAndAccept{ 

    tasksArray[taskKeyWhichIsDone].mark = false;
    
    //счётчик открытых задач
    countOpenTasks -=1;
}

// получить описание задачи по ключу
function getTask(int8 keyOfTaks) public view returns (Task){
    
    return tasksArray[keyOfTaks];
}

// удаление задачи по ключу
function removeTask(int8 taskKeyToRemove) public checkOwnerAndAccept{ 
    
    //счётчик открытых задач
    if (tasksArray[taskKeyToRemove].mark==true){
        countOpenTasks -=1;
        }
    //удаление
    delete tasksArray[taskKeyToRemove];
}

    constructor() public {
        // Check that contract's public key is set
        require(tvm.pubkey() != 0, 101);
        // Check that message has signature (msg.pubkey() is not zero) and
        // message is signed with the owner's private key
        require(msg.pubkey() == tvm.pubkey(), 102);
        // The current smart contract agrees to buy some gas to finish the
        // current transaction. This actions required to process external
        // messages, which bring no value (henceno gas) with themselves.
        tvm.accept();

    }
	}
